# Generated by Django 4.2.4 on 2024-09-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_remove_image_images_imag_created_d57897_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-created"], name="images_imag_created_d57897_idx"
            ),
        ),
    ]
